version: '3.7'
services:
    nginx:
        image: nginx:latest
        ports:
            - target: 80
              published: 80
              protocol: tcp
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
        depends_on:
            - client
            - server 
    client:
        image: hazardd/client:v1
        build:
            context: ./client
        ports:
            - target: 8089
              published: 8089
              protocol: tcp     
    server:
        image: hazardd/server:v1
        build:
            context: ./server
        ports:
            - target: 8084
              published: 8084
              protocol: tcp
    notification:
        image: hazardd/notification_server:v2
        build:
            context: ./notification_server
        ports:
            - target: 9000
              published: 9000
              protocol: tcp
    prizegen:
        image: hazardd/prizegen:big
        build:
            context: ./prizegen-big
        ports:
            - target: 9017
              published: 9017
              protocol: tcp
    textgen:
        image: hazardd/textgen:upper
        build:
            context: ./textgen-upper
        ports:
            - target: 9018
              published: 9018
              protocol: tcp
    numgen:
        image: hazardd/numgen:big
        build:
            context: ./numgen_big
        ports:
            - target: 9019
              published: 9019
              protocol: tcp
    db-connector:
        image: hazardd/db-connector:v1
        build:
            context: ./db_connector
        ports:
            - target: 5001
              published: 5001
              protocol: tcp
        depends_on:
            - mongo
            - server
    mongo:
        image: mongo:latest
        ports:
            - target: 27017
              published: 27017
              protocol: tcp

