apiVersion: v1
kind: Pod
metadata:
  name: numgen
  labels: 
    app: numgen
spec:
  containers:
    - name: numgen
      image: hazardd/numgen:small
      imagePullPolicy: "Always"
      ports:
      - containerPort: 9019
