apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
    labels:
        app: server
spec:
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
            - name: server
              image: hazardd/server:v1
              ports:
              - containerPort: 8084
              env:
              - name: "SERVER_PORT"
                value: "8084"
